apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pvc-claim
  namespace: jenkins
  labels:
    app: jenkins
    tier: frontend
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  claimRef:
    namespace: jenkins
    name: jenkins-pvc-claim
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.22.160
    # Exported path of your NFS server
    path: "/nfs/jenkins/data"
